### ISSUE TITLE
Final Digital PDF retains watermark

### ISSUE THREAD

**Issue by bob-in-columbia** [mnelson4/printmyblog#207]
Hi, Mike.
The test version of the PMB digital pdf looked as I wanted. I clicked looked good to get the non-watermarked version, but the new pdf retained the watermark although the message box notified me I was using one of my two final versions for this month.

Can you help?
Robert
[PMB L L H Digital 5.5 x 8.5.pdf](https://github.com/mnelson4/printmyblog/files/6177988/PMB.L.L.H.Digital.5.5.x.8.5.pdf)

```
{"php":"7.4.14","wp":"5.7","site_url":"https://www.rhamill.com","home_url":"https://www.rhamill.com","language":"en_US","public":"1","environment_type":"production","plugins_active":{"404page - your smart custom 404 error page":"11.3.0 by Peter Raschendorfer ","Advanced Import":"1.3.1 by AddonsPress ","Akismet Anti-Spam":"4.1.9 by Automattic ","Ample Themes Demo Importer":"2.2.6 by amplethemes ","BackupBuddy":"8.7.2.0 by iThemes ","Better Search Replace":"1.3.4 by Delicious Brains ","Breadcrumb NavXT":"6.6.0 by John Havlik ","Broken Link Checker":"1.11.15 by WPMU DEV ","Column Shortcodes":"1.0.1 by Codepress ","Content Aware Sidebars":"3.15.2 by Joachim Jensen - DEV Institute ","Duplicator":"1.4.0 by Snap Creek ","Enable Media Replace":"3.5.0 by ShortPixel ","Google Analytics for WordPress by MonsterInsights":"7.16.2 by MonsterInsights ","Gutentor - Gutenberg Blocks - Page Builder for Gutenberg Editor":"3.0.7 by Gutentor ","iThemes Security":"7.9.0 by iThemes ","iThemes Sync":"2.1.8 by iThemes ","Jetpack by WordPress.com":"9.5 by Automattic ","Popup Maker":"1.16.0 by Popup Maker ","Print My Blog":"3.0.0.alpha.027 by Michael Nelson ","ShortPixel Image Optimizer":"4.21.2 by ShortPixel ","Show-Hide/Collapse-Expand":"1.2.5 by Bunte Giraffe ","This Day In History":"3.8.1 by BrokenCrust ","WP-Optimize - Clean, Compress, Cache":"3.1.8 by David Anderson, Ruhani Rabin, Team Updraft ","Yoast SEO":"16.0.2 by Team Yoast "},"active_theme":{"name":"Ample Magazine Child (ample-magazine-child)","version":"0.1.9","author":"amplethemes","author_website":"http://amplethemes.com","parent_theme":"Ample Magazine Pro (ample-magazine-pro)","theme_features":"core-block-patterns, automatic-feed-links, title-tag, post-thumbnails, menus, html5, post-formats, custom-background, customize-selective-refresh-widgets, custom-logo, align-wide, custom-header, infinite-scroll, jetpack-responsive-videos, jetpack-content-options, widgets, editor-style"},"debug":false,"post_max_size":"512M","upload_max_size":"512M","effective_max_size":536870912,"ssl":true,"multisite":false,"projects":[{"title":"Life Liberty Happiness","generations":{"digital_pdf":"https://www.rhamill.com/wp-content/uploads/pmb/generated/8lwm7zU8dpGJvDam3yBO/digital_pdf/life-liberty-happiness.html","print_pdf":"https://www.rhamill.com/wp-content/uploads/pmb/generated/8lwm7zU8dpGJvDam3yBO/print_pdf/life-liberty-happiness.html"},"meta":{"_pmb_title":"Life, Liberty, and the Pursuit of Happiness","_pmb_subtitle":"Governmental, educational, and economic changes to make aspirations achievable"},"designs":{"digital_pdf":{"title":21201,"template":"Classic Digital PDF","meta":{"_pmb_header_content":["title","subtitle","date_printed"],"_pmb_post_content":["title","content"],"_pmb_page_per_post":"1","_pmb_font_size":"12pt","_pmb_image_size":"800","_pmb_image_placement":"snap-unless-fit","_pmb_page_width":"139.7mm","_pmb_page_height":"215.9mm","_pmb_internal_links":"remove","_pmb_external_links":"remove","_pmb_custom_css":null,"_pmb_default_alignment":"center","_pmb_font_style":"times new roman","_pmb_header_font_style":"arial","_pmb_use_theme":""}},"print_pdf":{"title":21203,"template":"Classic Print PDf","meta":{"_pmb_header_content":["title","subtitle","date_printed"],"_pmb_post_content":["title","content"],"_pmb_page_per_post":"1","_pmb_font_size":"12pt","_pmb_image_size":"400","_pmb_page_width":"127mm","_pmb_page_height":"203mm","_pmb_internal_links":"remove","_pmb_external_links":"remove","_pmb_custom_css":"article{line-height:2;}","_pmb_default_alignment":"center","_pmb_image_placement":"snap-unless-fit","_pmb_font_style":"times new roman","_pmb_header_font_style":"arial","_pmb_paragraph_indent":"1","_pmb_use_theme":""}}}}]}
```

**Comment by mnelson4** [comment]
hi Robert I've investigated and will hav ea fix for tonight...

**Comment by mnelson4** [comment]
Aha I think I got it @bob-in-columbia . 
Download the updated version here: https://github.com/mnelson4/printmyblog/archive/PRO/master.zip

If you visit the [Print My Blog "Account" page](https://i.imgur.com/P6FzoNl.png) the number of available downloads will sync (I saw one "live" download and I removed it so you should have 2/2 downloads available).

**Comment by mnelson4** [comment]
oh, and I see the title page isn't terribly well-centered for you. You can move it around and resize it with this bit of custom CSS (just add it to the design)

```
.post-21684.pmb-part h1.pmb-title{
    margin-top:2in;
    font-size:4em;
}
```
I'm thinking of adding a setting to control the font size of headings. Do you think that would be helpful for you? 
(And regarding centering I'm hoping to automatically center it once the upstream service adds support for it).

**Comment by bob-in-columbia** [comment]
I have read your comments and will with the new zip.

**Comment by bob-in-columbia** [comment]
Hi, Mike. I'm going in circles.
First, I clicked on the zip link you posted. It never returned. So I downloaded the zip file under the code button. Is that the zip?
I updated my site plugin and ran it. I did not get to the test of the watermark fix, because of the title page issue you mentioned. 
Instead of the title page, the first printed page is the title and first fragment of the first post. The meta content is available but the page was not generated. So I added a front matter entry of Title Page of Just Content. That didn't work either. I expect the cover page to be automatically created from the meta data. I must be missing a step.  

Similar question for copyright page. If I want a copyright page in the pdf, do I need to create a copyright blog entry to add into the front material?  

Thanks,
Robert

**Comment by mnelson4** [comment]
Hi @bob-in-columbia, sorry for the circles! Argh.

Yeah there's something funny about the link I provided to download the zip. It doesn't work for me either, actually, when I click it. But if I copy-and-paste it into my browser it *does* work. So I think GitHub is doing something weird. [Here's a video showing what I mean, and showing that if you just copy-and-paste it into your browser then it *does* work.](https://drive.google.com/file/d/1buDtQOxOYV92DRhFy1vOycVuHtVg2lkG/view). Sorry that's really annoying.

The zip file you downloaded is similar, but I don't think that's the PRO version of the plugin.

And for the copyright page, here's what you'd do:
* go to your project's "Edit Content" page
* at the bottom of the "Front Matter", click the "Click or drag here +" 
* give the new print material the title "Copyright" or whatever you want
* once it's added, click the pencil to edit the post. I added text like this:

> Copyright © 2021 Colin Michael Lucien Jonathan Nelson
> All rights reserved. No part of this book may be reproduced or used in any manner without the prior written permission of the copyright owner, except for the use of brief quotations in a book review.To request permission, contact the publisher at https://cmljnelson.blog/contact-me

TBH that was my first go at writing a copyright page, so you'll probably know better if it's leaving something out!

* Anyways, save the copyright print material, then close that tab.
* Change that article to be "Just Content"
* Save

You will be taken to the "Generate" page, and after you regenerate the project the copyright page will appear.

Here's a video showing what I mean: https://drive.google.com/file/d/1ZPs1ShW8ZTJjvLnyCLRxdRRxEaDVNHip/view

Note: the text will appear at the top of the page, but you probably want it to be centered? I'm working on a new section template that will be called "Centered Content" that will do exactly that. I'll let you know when that's ready.

**Comment by bob-in-columbia** [comment]
Thank you, Mike. I'll take the steps you suggest.

Of course, I am working to give a meaningful evaluation of your very useful plugin. 

FWIW. I have used the html supporting the digital pdf to create an free-flow eBook via Kindle Create.
The current activity is intended for digital pdf input to Kindle Create for a paperback book on Amazon.
Robert

**Comment by mnelson4** [comment]
Oh cool. I will have to try that too. Yes thank you for sharing! I think it will be great to share with others too (I think it will give them ideas, as honestly there isn't as much activity from others as I was hoping.)

**Comment by mnelson4** [comment]
Ok adding a copyright page will be much easier now with tonight's update!
You'll need to first update again (copy-and-paste this link into your browser: https://github.com/mnelson4/printmyblog/archive/PRO/master.zip) and then upload it to your site again.
When editing your project's content the section template options have changed.  See https://i.imgur.com/Kij0CWO.png I use that for my table of contents. "Just Content" was renamed to "Fullpage content", and there's a new "Centered Content", which just centers the post's content into the middle of the page.
Please let me know if you have any suggestions around how adding a copyright page could be easier for you.


Other things to mention:
* I see you've used another credit. I have a ton of extra credits for this month so restored the credit (just visit the account page again and it will re-sync)
* in my opinion in your project the font size seems a bit big. I would reduce it but maybe that size works better for you for some reason
* are you trying to have a blank page at the start? If so, I assume you'd like the little roman numeral "i" to not appear, right? (I can automatically remove that for blank pages)

**Comment by bob-in-columbia** [comment]
Yahoo! Thanks, Mike. The watermark is gone.
I had just read your new post. 

- I'm looking forward to trying the new, improved copyright page.
- Thanks for the extra credit. I spent several hours today learning that Kindle Create rejects the page header is too long. It sometimes flows to 2 lines, which their algorithm rejects. So I'll be recreating in PMB.
- I have vision problems. Maybe that explains the font selected.
- No, blank page at front is not something I consciously aimed for.

By the way, Kindle Create for paperback has its own front and back cover tools. 

The watermark issue is successfully resolved.

**Comment by bob-in-columbia** [comment]
Thanks, Mike.
I intend to post a review soon, after I devote a bit more effort to my particular effort.
Robert

**Comment by mnelson4** [comment]
Great to hear you're making progress!
Regarding the blank page at the front, it looks like you've created a "Title Page" print material and place it in your project's "front matter", but it's blank. That's making PMB print a (mostly) blank page at the start.
To remove that blank page, you should remove the "Title Page" from your project's "Front Matter". Here's a video showing what I mean: https://drive.google.com/file/d/1texrLvTUliang3RIJbr6Ni9uZxrwdLLi/view

But anyways, yes this issue is finished. Feel free to create new issues describing any novel problems you face.
Also, I'd like to share your creation with the rest of the users to give them some ideas for what's possible, when you're done with it.
