### ISSUE TITLE
Title Page, Byline, and Roman Numeral

### ISSUE THREAD

**Issue by bob-in-columbia** [mnelson4/printmyblog#221]
I am using the updated PMB Pro that you posted, attempting to improve the title page. Attached is the generated classic digital pdf which shows the title page takes 2 pages with the byline on the second page. Also page one has roman numeral at the bottom right.

I'd be happy if I could control (shrink) the title page font so that only one page would be required.

Although I looked at your new title page documentation, I am unable to pursue all aspects of it at this time.

[PMB L L H Digital Centered Title and Election Gallery.pdf](https://github.com/mnelson4/printmyblog/files/6268293/PMB.L.L.H.Digital.Centered.Title.and.Election.Gallery.pdf)

```
{"php":"7.4.14","wp":"5.7","site_url":"https://www.rhamill.com","home_url":"https://www.rhamill.com","language":"en_US","public":"1","environment_type":"production","plugins_active":{"404page - your smart custom 404 error page":"11.3.0 by Peter Raschendorfer ","Advanced Import":"1.3.1 by AddonsPress ","Akismet Anti-Spam":"4.1.9 by Automattic ","Ample Themes Demo Importer":"2.2.9 by amplethemes ","BackupBuddy":"8.7.2.0 by iThemes ","Better Search Replace":"1.3.4 by Delicious Brains ","Breadcrumb NavXT":"6.6.0 by John Havlik ","Broken Link Checker":"1.11.15 by WPMU DEV ","Column Shortcodes":"1.0.1 by Codepress ","Content Aware Sidebars":"3.15.2 by Joachim Jensen - DEV Institute ","Duplicator":"1.4.0 by Snap Creek ","Enable Media Replace":"3.5.0 by ShortPixel ","Google Analytics for WordPress by MonsterInsights":"7.17.0 by MonsterInsights ","Gutentor - Gutenberg Blocks - Page Builder for Gutenberg Editor":"3.0.8 by Gutentor ","iThemes Security":"7.9.0 by iThemes ","iThemes Sync":"2.1.8 by iThemes ","Jetpack by WordPress.com":"9.6 by Automattic ","Popup Maker":"1.16.1 by Popup Maker ","Print My Blog Pro":"3.0.0 by Michael Nelson ","ShortPixel Image Optimizer":"4.21.2 by ShortPixel ","Show-Hide/Collapse-Expand":"1.2.5 by Bunte Giraffe ","This Day In History":"3.8.2 by BrokenCrust ","WP-Optimize - Clean, Compress, Cache":"3.1.8 by David Anderson, Ruhani Rabin, Team Updraft ","Yoast SEO":"16.1.1 by Team Yoast "},"active_theme":{"name":"Ample Magazine Child (ample-magazine-child)","version":"0.1.9","author":"amplethemes","author_website":"http://amplethemes.com","parent_theme":"Ample Magazine Pro (ample-magazine-pro)","theme_features":"core-block-patterns, automatic-feed-links, title-tag, post-thumbnails, menus, html5, post-formats, custom-background, customize-selective-refresh-widgets, custom-logo, align-wide, custom-header, infinite-scroll, jetpack-responsive-videos, jetpack-content-options, widgets, editor-style"},"debug":false,"post_max_size":"512M","upload_max_size":"512M","effective_max_size":536870912,"ssl":true,"multisite":false,"projects":[{"title":"Life Liberty Happiness","generations":{"digital_pdf":"https://www.rhamill.com/wp-content/uploads/pmb/generated/8lwm7zU8dpGJvDam3yBO/digital_pdf/life-liberty-happiness.html","print_pdf":"https://www.rhamill.com/wp-content/uploads/pmb/generated/8lwm7zU8dpGJvDam3yBO/print_pdf/life-liberty-happiness.html"},"meta":{"_pmb_title":"Life, Liberty, and the Pursuit of Happiness","_pmb_subtitle":"Achieving the Goals of the Declaration of Independence","_pmb_issue":null,"_pmb_byline":"Robert Hamill","_pmb_date":null,"_pmb_cover_preamble":null},"designs":{"digital_pdf":{"title":21201,"template":"Classic Digital PDF","meta":{"_pmb_header_content":["title","subtitle","byline"],"_pmb_post_content":["title","content"],"_pmb_page_per_post":"1","_pmb_font_size":"12pt","_pmb_image_size":"800","_pmb_image_placement":"snap-unless-fit","_pmb_page_width":"139.7mm","_pmb_page_height":"215.9mm","_pmb_internal_links":"remove","_pmb_external_links":"remove","_pmb_custom_css":".post-22165.pmb-part h1.pmb-title{rn    margin-top:1in;rn    font-size:3em;}","_pmb_default_alignment":"center","_pmb_font_style":"times new roman","_pmb_header_font_style":"arial","_pmb_use_theme":""}},"print_pdf":{"title":21203,"template":"Classic Print PDf","meta":{"_pmb_header_content":["title","subtitle","date_printed"],"_pmb_post_content":["title","content"],"_pmb_page_per_post":"1","_pmb_font_size":"12pt","_pmb_image_size":"400","_pmb_page_width":"127mm","_pmb_page_height":"203mm","_pmb_internal_links":"remove","_pmb_external_links":"remove","_pmb_custom_css":"article{line-height:2;}","_pmb_default_alignment":"center","_pmb_image_placement":"snap-unless-fit","_pmb_font_style":"times new roman","_pmb_header_font_style":"arial","_pmb_paragraph_indent":"1","_pmb_use_theme":""}}}}]}
```

**Comment by mnelson4** [comment]
Ok thanks for the debugging info @bob-in-columbia !
I've released PMB Pro 3.0.1 which:
* removes the roman numerals from the first page of front matter (normally the title page)
* adds a new setting to change the title page's header size (and the part header, for those who use those). I'd trying setting it to `3em`.
* fixes a bug that was adding custom CSS to all print-ready PDFs which made all lines be double-spaced. I'm afraid for existing users like yourself though you'd need to manually remove the lines (on the "Customize Print-Ready PDF Design" step, go to "Custom CSS" at the very bottom and delete its content. See https://i.imgur.com/kNTfa7X.png)

Also, if your PDF is meant for print, I would think using the Print-Ready format and the Classic Print-Ready PDF would be a better choice, no? With that design, page numbers are always on the outside bottom corner of the page, which would look better when viewing two pages at a time, right? (When doing this you'll need to set the page size in this design too).
Or is there some reason you preferred the Digital PDF?

**Comment by bob-in-columbia** [comment]
Thanks Mike, for the fix and explanations. I'll be trying again today. 
Re: my choice of digital pdf. I tried both versions of the Print-Ready pdf. The Kindle Create program accepted them, but downstream errors (later I discovered e.g. page header too wide) occurred. I decided to focus on one pdf. For no specific reason that I can recall, I picked Digital PDF. Thanks again, Robert

**Comment by bob-in-columbia** [comment]
Excellent, Master of PMB. Worked just as you described. The additional font options are a very useful addition. Robert

**Comment by mnelson4** [comment]
Ok good to hear the changes worked as expected! Hopefully these improvements will be useful for other diwn the road too.
