### ISSUE TITLE
Images all show up on separate line

### ISSUE THREAD

**Issue by prueker** [mnelson4/printmyblog#24]
I'm using a lot of images at medium size, which fit side-by-side on my blog on one line.
However when I print using the plugin, every image is on a separate line even though there are no line breaks in the source code of my blog between those pictures.

I'm using the Twenty-Twelve Theme and I am using FooBox plugin, but the plugin generally only affects when you click on an image, not the medium size in the post itself.

Blog:
![image](https://user-images.githubusercontent.com/17036240/60222068-d7ed0e00-9830-11e9-99ca-6cdf69a74aae.png)

Printed page:
![image](https://user-images.githubusercontent.com/17036240/60222091-eaffde00-9830-11e9-94f2-7ce9db75bff8.png)

**Comment by mnelson4** [comment]
Hmmmm good point.

Here's what's going on: the images are getting wrapped in a DIV that forces them to not get chopped in half across physical pages. A side-effect is that they are now all on new lines.
That's probably good for big images, but not smaller ones.

Are the images in a gallery?

Can you send me a link to your blog post with this issue, then I can inspect the HTML, and that might give me some better idea of how to fix.

**Comment by prueker** [comment]
These ones that all get newlined in the print are not in a gallery, they are just single standing images.

I hear you on the wrapping them in a DIV to prevent cutting, so I'm wondering of if maybe you could detect if there's two images next to each other block-wise and then wrap them together into one div.

Link to the post I used as illustration: https://slingtsi.rueker.com/2019/06/10/flaps-priming-aileron-inventory/

**Comment by mnelson4** [comment]
Hi again @prueker, I've managed to get around to working on this. My solution was just to leave thumbnail and medium images untouched (whereas larger images I'm wrapping in a special div tag.) From my testing in Firefox, the browser still doesn't chop images in half (whereas I recall it did for larger images, which is what the special div tag helped prevent).
Would you mind testing the branch where I've made the fix before I release it? Download the version here: https://github.com/mnelson4/printmyblog/archive/BUG/dont-wrap-medium-images.zip, it's version 1.9.4. After you upload it to your site (preferably a test site), deactivate the old version of Print My Blog, and then activate this version 1.9.4, and see if it resolves this issue (btw, your other issue is on my radar afterwards.) Please let me know how it goes. 
If you can't or don't have time, please let me know in the next couple days. Thanks! 😁

**Comment by prueker** [comment]
Hey,

Hey, the last two days have been hectic, I'll try to see if I can test it tonight and I'll let you know.

-Philip
________________________________

**Comment by prueker** [comment]
Hey,

I tested the fix and looks like it's working as intended.
Example here:
[cid:11b4dead-343e-45c5-85dd-9016223116c1]

Thanks for the fix.

-Philip
________________________________

**Comment by mnelson4** [comment]
Great, thanks for double-checking Philip. This change just got released as version 1.9.4 🍾
