### ISSUE TITLE
editor layout issues

### ISSUE THREAD

**Issue by mnelson4** [mnelson4/printmyblog#256]
On https://github.com/mnelson4/printmyblog/issues/106#issuecomment-875162152 @ericjung remarked that the project's area is flowing to the next line which isn't very usable.
Unfortunately I'm not reproducing the issue.

I'm hoping @ericjung can help me know which browser he's using, which content, and what screen size.

**Comment by ericjung** [comment]
@mnelson4 Sure:

Chrome 91.0.4472.114 (Official Build) (x86_64) -- latest version as of today
MacOS Big Sur 11.0.1 -- I see 11.4 is available and can update if you think that will help
MacBook Pro 16-inch 2019 with Intel UHD Graphics 630

It's not wrapping for me today.

Having said that, I still think you should consider making the *Select Content* section full-width with a *Search* button in the lower-right or lower-left. Then search results and project content below. This is a common pattern I've seen elsewhere.

As I mentioned in [here](https://github.com/mnelson4/printmyblog/issues/106#issuecomment-875162152), I think you should consider two side-by-side list boxes still but something more [like this](https://jakezatecky.github.io/react-dual-listbox/) than what I posted before:

![image](https://user-images.githubusercontent.com/5875610/124774773-4f170b80-defb-11eb-9268-74cd612041a1.png)

That's the 6th image on the page. Notice in particular this one has up/down arrows on the right for reordering. This is a classic design that dates back even to the 1990s. It also does not eliminate drag-and-drop. Some of these widgets allow both drag-and-drop as well as arrows for movement left, right, up, and down. I've used this particular widget in my projects, but I doubt your codebase supports React. There are many of these out there, some good ones from jQuery, too, if that is an option for your codebase.

So your bold headings in the right-side list would be *Front Matter*, *Main Matter*, *Back Matter*.

**Comment by mnelson4** [comment]
The updated layout in 3.4 is quite different and I hope won't have this same issue.
@ericjung can you still reproduce after updating to 3.4.0?

**Comment by ericjung** [comment]
It still looks good with 3.4.0. I think you can close.

**Comment by mnelson4** [comment]
Right on. Please reopen if you see it again.
