### ISSUE TITLE
Photo Heavy Blog

### ISSUE THREAD

**Issue by kyandell** [mnelson4/printmyblog#260]
I love this plugin. Thank you. Two questions:

One, the photo snapping moves photos but some have captions under them that are in the regular text body so moving the photo leaves an orphan description. Is there a way to have the photo just start on the next page so the text doesn't get out of order with the photo.

Two, I'm essentially archiving to shut down the website. So is there a way to also save a pdf without photos at all. This way I have a shorter, easier pdf that preserves all of my stories and such without the images at all.

As soon as I work out these personal issues I look forward to paying for the plugin to save and print several iterations of the document. This plugin is saving me months of work. Thank you. Also, I'm woefully non-technical so if this has been answered a 100 ways below I apologize. I read the guide and these posts an didn't see anything.

**Comment by mnelson4** [comment]
Hi @kyandell thanks for your questions.
Are you currently using quick print or pro print? If quick print, can you share the URL of your site? If pro print, can you use the plugin’s help page to create a new GitHub issue with the debugging data?
That will help me better understand your issues.

**Comment by kyandell** [comment]
Thanks. Pro. I think I just did the help page thing.

**Comment by mnelson4** [comment]
Great thanks.
Yes phot snapping does leave captions behind, which is a major deficiency.
You should be able to remove images entirely by setting their maximum size to 0 on the “customize design” stage, but that currently has another problem (the captions sudddenly become super tall). I’ll update you when I have a fix for those items (hopefully sometime in the next week)

**Comment by mnelson4** [comment]
Hi again @kyandell.
I've had some time on my computer to look into this. I realized that both things you want are currently doable.

To change the Classic Digital PDF, do the following:
1. From the WordPress admin dashboard, go to "Pro Print".
2. Hover over the project you want to edit. You'll see a bunch of options appear.
3. Click "Customize DIgital PDF Design"
4. Expand the "Image Settings" area
5. Change "Image Placement" to "Don't move"

See https://i.imgur.com/jzmMwvK.png

Alternatively, if you want to remove the images altogether, you can set the maximum image height to 0 (also in the previous screenshot).

If you also want to also change the Print-Ready PDF, repeat the above but on step 3 click "Customize Print-Ready PDF Design" instead.

Please let me know if you have any troubles.

**Comment by mnelson4** [comment]
Also, just a tip: if you were using categories or tags, it might be good to organize your recipes by category. Eg have a category of "Desserts", and another of "Main Courses", etc. For that you could create parts for each category, and then put the relevant recipes within its corresponding part. Eg I do something similar here: https://youtu.be/un7EnpDG2qs?t=275
But if you prefer keeping your posts ordered by date, then what you have is probably best.

**Comment by kyandell** [comment]
Thank you so much for your help. I am so appreciative.

 

Kelly Dean Yandell

 ***@***.***> ***@***.***

 <http://www.themeaningofpie.com/> www.themeaningofpie.com

 <http://www.kellyyandell.com/> www.kellyyandell.com

**Comment by mnelson4** [comment]
Ok I’ll close this issue then. Please add another comment if you still have trouble with disabling image floating or removing images. For other stuff, please open a new issue.
And if you have time, I’d appreciate you leaving a review here: https://wordpress.org/support/plugin/print-my-blog/reviews/
Take care!
