### ISSUE TITLE
random code on edit pages

### ISSUE THREAD

**Issue by generalsynod** [mnelson4/printmyblog#309]
There is some code that appears to be from PMB on our edit pages. See attached.
![Screenshot 2022-03-04 at 10 31 22 AM](https://user-images.githubusercontent.com/8311607/156792397-7b65b4cf-9dd2-4b7d-a287-8e8fe5fc248e.png)

**Comment by mnelson4** [comment]
Ah I see the problem. I had changed my code around and forgot to test how that would affect the classic editor.
That URL that's being printed out should have been HTML of a button (using that URL) for copying the post as a "Print Material" for editing in a PMB project.
I have a fix for it now, but I probably won't release until Monday (unless it's kinda urgent)

**Comment by generalsynod** [comment]
Not urgent at all! Thanks!

**Comment by mnelson4** [comment]
oups forgot to mention: this should be resolved in the update 5 days ago. Please let me know if you're still having any issues
