### ISSUE TITLE
Would like to include Author of blog posts

### ISSUE THREAD

**Issue by John-Nottingham** [mnelson4/printmyblog#36]
Thanks for Print My Blog.  We are shortly closing down six years of blog posts by several authors. I have created a PDF for each year but they don't show authors. Also, would really like to create a PDF for each author. Any chance? Thanks.

**Comment by mnelson4** [comment]
Hi John! I will try to add those features for you this month. Hopefully that will be on-time. (FYI no, I don't respond like this to all feature requests! But it's not the first time I've heard or at least thought about adding those features.)
I'll update this issue once those features are ready to be tested. Would you mind testing those features once I've developed them? (I'll provide instructions.)

**Comment by John-Nottingham** [comment]
Sure. Thanks !  Month is fine, stretching to 2020 not so good. BTW we are on php 7.1 and wp 5.2.4

**Comment by mnelson4** [comment]
Did I say a month? I meant a day! :wink: 

I have a new version of Print My Blog (1.14.0) that adds these features. You can [download it here](https://github.com/mnelson4/printmyblog/archive/FET/authors2.zip).
To try it out, do the following:
1. Deactivate the old version of Print My Blog on your site
2. Upload that zip to your WordPress website (by going to the WordPress dashboard at wp-admin, then Plugins, then Add New, and find "Upload Plugin" towards the top). 
3. Activate it

On the print setup page, under "Filters" you should see a new filter called "Authored By". You should be able to search for the authors in there. (Note: I've noticed some security plugins may prevent this from working, let me know if that's the case for you.) This should limit the posts to only those written by that user, and, if you've checked "Filters Used" (under "Header Content to Print") the top of the printout should mention which user you're filtering by.

Also, under "Post Content to Print" you should see a new checkbox for "Author". Checking this should show each post's author.

Let me know how it goes!

Note: I made this assuming you'd only want to filter by a single author, not by multiple authors (so you either get posts by ALL authors, or just one). Do you think you'd ever want to show a printout of posts by 2 authors?

**Comment by John-Nottingham** [comment]
Wow, Mike, that is fantastic! Glad I got my donation in yesterday, would have felt guilty otherwise, ha ha.  Will give this a go later today.  Your assumption about single/authors is right for me.

**Comment by John-Nottingham** [comment]
Fantastic!  Works perfectly (based on two quick tests).  Selection by author- ✔️ Display of author when author selected and when author not selected-tick.  Will do more stuff later but need to do my day job stuff now.  Let me know if you want an specific tests.  So far I am only choosing output for pdf but plan to try ebook later. Thanks again, Mike, this is wonderful

**Comment by mnelson4** [comment]
> Glad I got my donation in yesterday, would have felt guilty otherwise, ha ha. 

Oh that was you! Thanks. (Although on that topic, the "guilt factor" is an aspect of asking for donations that I'm realizing I don't like...)

Yeah if you'd like to test an ebook that would be good, but what you've already done is very helpful. I'll test on one of my live sites today or tomorrow, and if it's good, will probably then release it.

**Comment by John-Nottingham** [comment]
Your appeal for funds is fine.  I always support those who make things for the better.  Just waited till I was sure it worked! Ha ha. Initially the plugin gave us White Screen of Death.  Our dormant site needed to have the WP version updated, all the plugins updated, the php  version upgraded then downgraded a bit due to an incompatible plugin.  Then your plugin worked perfectly, so I donated.

**Comment by John-Nottingham** [comment]
Crested an book and used recommended Firefox plugin to create kindle ebook and viewed on my kindle.  For an image rich site, as expected from your helpful guide, not a great result. But works.  For us, pdf better

**Comment by John-Nottingham** [comment]
Created not crested.  And I wanted to say your guides to the two plugins are VERY helpful. Thanks!

**Comment by mnelson4** [comment]
I just tried it on one of my live sites with the Wordfence security plugin, and Wordfence is preventing me from listing the site's users (although it should be allowing authenticated users through.) So I'd like to take a bit more time to fix that before releasing.

Sorry to hear you got a white screen of death originally! I've been trying to prevent those. Do you know what version of WordPress, PHP, and Print my Blog you were using at the time?

**Comment by mnelson4** [comment]
Ok I fixed the issue with Wordfence, so I've released this as 1.14.0 :tada:. So I'm going to close this issue...

having said that, it may be good to create new issue for that white-screen-of-death you got earlier (along with the WordPress, PHP, and version of Print My Blog you were using, if you can recall). 

And thanks for letting me know those YouTube videos were helpful. I really didn't spend too much effort on them, but it sounds like they're quite a significant help so I'll be more inclined to keep making them in the future.

Anyways, thanks @John-Nottingham ! Please let me know if you see any further issues.

Lastly, if you haven't already and have time, [adding a [review on wordpress.org](https://wordpress.org/support/plugin/print-my-blog/reviews/) would be the icing on the cake!
