### ISSUE TITLE
CPTs add by CPT UI are not options for content in "Edit Project Content"

### ISSUE THREAD

**Issue by Shelob9** [mnelson4/printmyblog#371]
My site has a CPT `doc` added by a code snippet. That shows in the list of posts. The CPT `Tutorial` I added with CPT UI is not showing up. 

![Screenshot 2023-04-19 180240](https://user-images.githubusercontent.com/1994311/233209765-d1ec09e9-7aa4-403e-b233-4899513604af.jpg)

* Print My Blog: Version 3.3.0 
* WordPress: 6.2
* PHP 7.4
* Active Plugins:

ActiveCampaign Postmark (Official) | Version 1.18.1 by Andrew Yates & Matt Gibbs \| Auto-updates disabled
Auto Login | Version 1.0 by <a href='http://www.cloudaccess.net/' target='_blank'>CloudAccess.net</a> \| Auto-updates disabled
Code Block Pro | Version 1.15.0 by Kevin Batdorf \| Auto-updates disabled
Code Snippets | Version 3.3.0 by Code Snippets Pro \| Auto-updates disabled
ConvertKit | Version 2.1.3 by ConvertKit \| Auto-updates disabled
Custom Post Type UI | Version 1.13.5 by WebDevStudios \| Auto-updates disabled
Editor Plus | Version 2.9.15 by Munir Kamal \| Auto-updates disabled
Embed Calendly | Version 3.2 by Embed Calendly, Shycoder \| Auto-updates disabled
GenerateBlocks | Version 1.7.3 by Tom Usborne \| Auto-updates disabled
Gutena Forms - Contact Forms Block | Version 1.0.9 by ExpressTech \| Auto-updates disabled
Hello Dolly | Version 4000 by Matt Mullenweg \| Auto-updates disabled
Limit Login Attempts Reloaded | Version 2.25.15 by Limit Login Attempts Reloaded \| Auto-updates disabled
oEmbed Gist | Version 4.9.1 by Takayuki Miyauchi \| Auto-updates disabled
Otter – Page Builder Blocks & Extensions for Gutenberg | Version 2.2.4 by ThemeIsle \| Auto-updates disabled
Plugin Machine Docs | Version 0.0.1 by Josh Pollock \| Auto-updates disabled
Print My Blog | Version 3.3.0 by Michael Nelson (Latest version: 3.23.2) \| Auto-updates disabled
Public Post Preview | Version 2.10.0 by Dominik Schilling \| Auto-updates disabled
Really Simple SSL | Version 6.2.4 by Really Simple Plugins \| Auto-updates disabled
Safe Redirect Manager | Version 1.11.1 by 10up \| Auto-updates disabled
SEO SIMPLE PACK | Version 3.2.0 by LOOS,Inc. \| Auto-updates disabled
Super List Block | Version 0.1.1 by Aurooba Ahmed \| Auto-updates disabled
Upcylced Found Objects | Version 0.5.0 by Imaginary Machines \| Auto-updates disabled
WordPress Importer | Version 0.8 by wordpressdotorg \| Auto-updates disabled

**Comment by mnelson4** [comment]
Thanks, this is the plugin you're using right? https://wordpress.org/plugins/custom-post-type-ui/

**Comment by mnelson4** [comment]
I just checked and a post type registered with Custom Post Type UI shows up, so long as you haven't set "Exclude from Search" to "True".
What have you set "Exclude from Search" to?
(To be exact, here's the code that selects the post types: `get_post_types(array( 'exclude_from_search' => false ));`. TBH I don't exactly recall why.)

**Comment by Shelob9** [comment]
@mnelson4 Yes, that is the plugin. 

Also, yes I had it set to true, changing it to true solved my issue. Thank you!

**Comment by mnelson4** [comment]
Ok good to hear the issue is solved. Although I’m reviewing why set `’exclude_from_search’ = > false` anyway. I think it’s just attempting to exclude internal custom post types (like menus, revisions, orders, etc). There might be a better way…

**Comment by mnelson4** [comment]
Oh weird-- I just realized you're using version 3.3.0 of my plugin, but the latest version is 3.23.2 on Freemius and 3.22.0 on WordPress.org. How did you get a version 3.3.0?? (I'm hoping I don't have an expired link to that somewhere.)

**Comment by Shelob9** [comment]
I downloaded from your site and then installed

**Comment by Shelob9** [comment]
I downloaded it from your site.

![Screenshot_20230422-112939](https://user-images.githubusercontent.com/1994311/233793343-e66438c2-8e00-4f04-817c-8d2a621f8d90.png)

**Comment by mnelson4** [comment]
Oh that’s weird. Also embarrassing. Sorry, but where on the site?
