### ISSUE TITLE
3 basic tests

### ISSUE THREAD

**Issue by szepeviktor** [mnelson4/printmyblog#44]
I work for developer teams. I talk them into using the following zero-coverage tests in CI:

1. syntax check
2. coding standard (much more than how you indent your code!)
3. static analysis

It makes your code robust without writing a single test.
Please consider introducing all three.

**Comment by szepeviktor** [comment]
e.g.

1. jakub-onderka/php-parallel-lint
1. PSR-12
1. @phpstan

**Comment by szepeviktor** [comment]
also frontend parts deserve to be checked: eslint, PrettyCSS, SVGLint

**Comment by mnelson4** [comment]
those all sound like great things to add, thanks. I'm not sure when I'll get around to adding those, but I do expect the need for those tools to grow as the project does too.
