### ISSUE TITLE
Auto-deploy to WP.org

### ISSUE THREAD

**Issue by szepeviktor** [mnelson4/printmyblog#46]
Would you welcome a feature that deploys printmyblog to WP.org when `  * Version: 2.1.3` changes in the main plugin file?

**Comment by mnelson4** [comment]
That sounds awesome yes. But it would probably also need to run some automated task to remove all the build and configuration files

**Comment by szepeviktor** [comment]
It would not be a copy operation but something aware of the contents of `.gitattributes` file.

**Comment by szepeviktor** [comment]
See https://github.com/10up/action-wordpress-plugin-deploy

**Comment by szepeviktor** [comment]
a very tricky shell script: https://github.com/10up/action-wordpress-plugin-deploy/blob/develop/entrypoint.sh
