### ISSUE TITLE
Large export

### ISSUE THREAD

**Issue by sfdonut** [mnelson4/printmyblog#56]
I have 3222 blog posts. I've tried Safari and Chrome to export as a PDF and Print and both don't work. It would be nice if I could select a date range, this would help keep the file size down.

**Comment by mnelson4** [comment]
Hi @sfdonut, sorry you’re having trouble. FYI there is an option to filter by date: on the print setup page, click “show options” then use “Posted After (and Including)” and/or “Posted Before (and Including)”

Even so, I’ve seen PDFs that big get generated with Print My Blog. What error are you getting? If you like, what is the site having trouble?

**Comment by sfdonut** [comment]
Thanks for the feedback. Everything works great if I use the date range filter. Each of my posts has 1-10 photos in them, so the size adds up.

**Comment by mnelson4** [comment]
Ya ok. I’d be interested to try your site and see if I can reproduce the error, to try to avoid this issue for others.

**Comment by sfdonut** [comment]
I would love to help out, but my site is a personal site.

**Comment by mnelson4** [comment]
No worries then. FYI you can also contact me directly via my blog: https://cmljnelson.blog
But it sounds like you’ve got things working well enough for you.
All the best! I think I’m good up close this ticker now.
