### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by mnelson4** [mnelson4/printmyblog#7]
It would be great to have a table of contents, showing page numbers of posts or something. It’s doable with CSS, but not all browsers support it. See https://alistapart.com/article/boom

**Comment by bob-in-columbia** [comment]
Keep up the great work, Michael Nelson.
 A table of contents would be a great addition for my use. [My blog](https://www.mentalconstruction.com/) contains an investigation into  thinking as shaped by neural properties. I want to print it in a book format.

**Comment by mnelson4** [comment]
Thanks! Cool. I take it you're wanting to make a print book? Or an e-book? I think the way I'll build the table of contents will be different for the two of them.

**Comment by bob-in-columbia** [comment]
Thank you for your plugin. It's excellent.
I want both to have table of contents, the printed book for my shelf and the eBook to share.
At the moment, I'm converting the html output with Calibre structure rule that yields a one-to-one blog to table of contents.

**Comment by mnelson4** [comment]
Awesome. I googled it and found this tutorial on how to add a table of contents with Calibre: http://blog.calibre-ebook.com/2013/04/magic-with-toc-edit-or-create-toc-for.html

**Comment by mnelson4** [comment]
FYI This is going into pro

**Comment by bob-in-columbia** [comment]
Michael, ToC is a great feature to add to your plugin. I can't wait. Robert

Mental Construction
Neurons form inexact matches that shape our mental world
 

    On Thursday, October 8, 2020, 3:43:54 AM EDT, Mike Nelson <notifications@github.com> wrote:  
 
 


FYI This is going into pro

**Comment by mnelson4** [comment]
This is added to pro (which itself is under construction) but I’m going to close this issue because this, itself, doesn’t need any more work
