### ISSUE TITLE
Sometimes settings not saving

### ISSUE THREAD

**Issue by mnelson4** [mnelson4/printmyblog#71]
Sometimes folks try to save the frontend print buttons' settings and they won't "stick"/save. (Curiously, both reports have said they experienced this on a second website.)
See https://wordpress.org/support/topic/save-settings-4/#post-12847137 and https://github.com/mnelson4/printmyblog/issues/66#issuecomment-625463436

**Comment by Werner-Honkomp** [comment]
My first website works now with the print button as I expected.
Now I installed yours plugin Print My Blog on an other website, but it do not accept to activate the option for “Show visitors buttons to print your posts?”
If I activated by “Setting” the print option and saved it, looks like ok. If click on “Settings again, the print option is blank.
I changed the the template and deactivated all plugins, without success.
Here the website:
https://heimatverein-lohne.de/
Have you an idea? Thank you.

**Comment by mnelson4** [comment]
Aha, I think I figured it out. I think your database doesn't support having emojis in it, probably because you're using some other database character set or collation.

@Werner-Honkomp would you mind trying my fix before I make it live for everyone?
1. Download the new version from here: https://github.com/mnelson4/printmyblog/archive/BUG/66/checkmarks.zip
2. Go to your Wordpress dashboard, click plugins, then "add new", then "upload" and select the zip file you just downloaded
3. Deactivate the previous version Print My Blog
4. Activate the new version of Print My Blog
5. Try saving the Print My Blog print settings again. They should work properly (although it should automatically remove the emojis from the print button labels, which I don't think your database supports)

**Comment by Werner-Honkomp** [comment]
Hello Michael,

After installation of the new plugin I deactivate and deleted the old 
plugin.
The setup option works now und the print-button (Drucken) shows under 
the article (with css modificatons) as I expected.
https://heimatverein-lohne.de/fahrt-in-die-lohner-partnerstadt-rixheim/
But the next print page is not correct now, because it is not translated 
to German words, the themes-styles could be lost also.

My provider wrote (translated by Goggle):

We generally support the collation for the use of emojis. The error 
usually occurs when the selected table collation does not support these 
characters.

Werner Honkomp


Am 18.05.2020 um 19:48 schrieb Mike Nelson:

**Comment by Werner-Honkomp** [comment]
I got now a warning message from Wordpress:

Hallo!

Seit WordPress 5.2 gibt es eine eingebaute Funktion, die erkennt, wenn ein Plugin oder ein Theme einen fatalen Fehler auf deiner Website verursacht, und dich deswegen mit dieser automatisierten E-Mail benachrichtigt.

In diesem Fall hat WordPress einen Fehler in einem deiner Plugins, Print My Blog, abgefangen.

Besuche zunächst deine Website (https://heimatverein-lohne.de/) und überprüfe sie auf sichtbare Probleme. Besuche als nächstes die Seite, auf der der Fehler aufgetreten ist (https://heimatverein-lohne.de/wp-admin/tools.php?page=print-my-blog) und prüfe, ob es sichtbare Probleme gibt.

Bitte kontaktiere dein Hosting-Unternehmen, um Unterstützung bei der weiteren Untersuchung dieses Problems zu erhalten.

Wenn deine Website fehlerhaft zu sein scheint und du nicht mehr wie gewohnt auf dein Dashboard zugreifen kannst, hat WordPress jetzt einen speziellen „Wiederherstellungsmodus“. Auf diese Weise kannst du dich sicher in deinem Dashboard anmelden und weitere Untersuchungen durchführen.

https://heimatverein-lohne.de/wp-login.php?action=enter_recovery_mode&rm_token=6Yi2zTgvBmCPAwrHmYnuvO&rm_key=CCfHLACeJR2GZhaqraOyxj

Um deine Website zu schützen, läuft dieser Link in 1 Tag ab. Aber keine Sorge: Ein neuer Link wird dir per E-Mail zugeschickt, wenn der Fehler nach Ablauf der Frist erneut auftritt.

Wenn du Hilfe bei diesem Problem suchst, wirst du möglicherweise nach einigen der folgenden Informationen gefragt:
WordPress-Version 5.4.1
Aktuelles Theme: 1st Tec B-01 (Version 1.1.1)
Aktuelles Plugin: Print My Blog (Version 2.4.2)
PHP-Version 7.3.10



Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 22 der Datei /kunden/93849_49393/webseiten/wordpress/wp-content/plugins/printmyblog-BUG-66-checkmarks/templates/partials/content_options.template.php verursacht. Fehlermeldung: Uncaught Error: Call to a member function getHtmlForShortOptions() on null in /kunden/93849_49393/webseiten/wordpress/wp-content/plugins/printmyblog-BUG-66-checkmarks/templates/partials/content_options.template.php:22
Stack trace:
#0 /kunden/93849_49393/webseiten/wordpress/wp-content/plugins/printmyblog-BUG-66-checkmarks/templates/partials/display_options.template.php(8): include()
#1 /kunden/93849_49393/webseiten/wordpress/wp-content/plugins/printmyblog-BUG-66-checkmarks/templates/setup_page.template.php(112): include('/kunden/93849_4...')
#2 /kunden/93849_49393/webseiten/wordpress/wp-content/plugins/printmyblog-BUG-66-checkmarks/src/PrintMyBlog/controllers/PmbAdmin.php(158): include('/kunden/93849_4...')
#3 /kunden/93849_49393/webseiten/wordpress/wp-includes/class-wp-hook.php(287): PrintMyBlog\controllers\PmbAdmin->renderLegacyAdminPage('')
#4 /kunden/93849_49393/webseiten/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /kunden/93849_49393/webseiten/wordpress/wp-includes/p



Am 18.05.2020 um 19:48 schrieb Mike Nelson:

**Comment by Werner-Honkomp** [comment]
I deactiveted the Plugin Post My Blog - because the Wordpress warning.

**Comment by mnelson4** [comment]
Hmmmm sorry I didn't get a notification for your update. I'm going to look into that error...

**Comment by mnelson4** [comment]
Aha, I see what the error was. Thankfully it only occurred on the admin page. If you re-download from https://github.com/mnelson4/printmyblog/archive/BUG/66/checkmarks.zip it should be fixed now

**Comment by Werner-Honkomp** [comment]
It works now:  
https://heimatverein-lohne.de/bilderschau-mit-dicke-bohnen-in-der-gaststaette-kalvelage-brockdorf/
Is it able at the preview print-page, change the word "Return" to "Zurück" ?
Thank you:
Werner

**Comment by mnelson4** [comment]
Great, I've released version 2.4.2 on WordPress.org now.
> Is it able at the preview print-page, change the word "Return" to "Zurück" ?

Yes, but not by me. The German translations are provided by the community. You can submit translations here: https://translate.wordpress.org/projects/wp-plugins/print-my-blog/dev/de/default/ and then you'll just need to wait for someone from the German WordPress Translations team to approve).

Ok I'm marking this issue as resolved. 🎉
