### ISSUE TITLE
Tablepress Plugin Problems

### ISSUE THREAD

**Issue by starstuff2020** [mnelson4/printmyblog#79]
Hi 

I use a very handy plugin called "tablepress" https://wordpress.org/plugins/tablepress/

If I utilize images in a tablepress table it results in the entire table going off the edge of the page on my print my blog .pdf
![TP Problem](https://user-images.githubusercontent.com/64659466/87701007-1b702e00-c74c-11ea-9102-d9993e3142b1.png)

Here are the settings:
![TP settings](https://user-images.githubusercontent.com/64659466/87701233-7bff6b00-c74c-11ea-8f5c-504f84702aeb.png)

Any idea how to resolve this problem?

Thanks so much.

**Comment by mnelson4** [comment]
Hi Peggy, thanks for the link to the plugin and the screenshots. Could you also send me a link to the site where you’re having the issue? That will also be really helpful.

**Comment by starstuff2020** [comment]
Hi Mike,  

https://goyimgazette.com/tablepress-test/
includes 2 tablepress tables that are running off the edge of the page.

I tried both "print now" (creating pdf by admin) and "settings" (adding button to page).  Both same results.

(I am using chrome)

Let me know if you need anything else.  

Peggy

**Comment by mnelson4** [comment]
I looked into it for a bit and have a little bit of progress.
I found Firefox seems to handle printing the table OK (no overflow) but saw the problem in Chrome. In Chrome you can fix it by scaling the page down to 80%. See https://drive.google.com/file/d/1EISlKb1iD54ZfrBlgQxI-Ze3HJ3-Dkk1/view

But ya, it seems often browsers struggle laying out tables in paged media. I'm hoping the Pro version, which will use Prince XML, will handle them better.

**Comment by starstuff2020** [comment]
Thanks for the tip Mike!  
You just saved me tons of time having to delete them with Adobe Pro and reinserting.
(I used the 80% trick.)

**Comment by mnelson4** [comment]
Great! But I’ll leave this open as a reminder to test tablepress with pmb pro when it’s ready

**Comment by mnelson4** [comment]
I tried table press again with both pmb pro and quick print and didn’t see any such issues, so I’m hoping this is fixed
