### ISSUE TITLE
2.9.2 update - results in pdf with no images

### ISSUE THREAD

**Issue by starstuff2020** [mnelson4/printmyblog#80]
I updated this morning and now "print" button results in document with NO images for my page.  I've tried to go back to a previous version (2.7.2) and am having the same issue.  Nothing else has changed with my theme or plugins.  I have tried both firefox and chrome with same results.

UPDATE:  Corrected problem by changing the images size to 3/4 (large) 

![pmb](https://user-images.githubusercontent.com/64659466/90983243-836f1c80-e521-11ea-8839-b1e005dbef79.png)

**Comment by mnelson4** [comment]
Thanks for reporting the issue @starstuff2020. Can you provide me with a link to where you’re having the problem?

**Comment by mnelson4** [comment]
Ya good was an issue in an update that got corrected a couple months back but I forgot to update this ticket. Thanks for reporting it!
